### ISSUE TITLE
Container restart when pocketmine crash

### ISSUE THREAD

**Issue by kfern** [crscheid/pocketmine-mp#10]
Hello!

Can I configure docker container auto-restart when pocketmine server crash? How?

Thanks in advance

**Comment by crscheid** [comment]
Yes, but outside the scope of this project. When you run the container, either via `docker run` or `docker-compose`, you can define a restart policy.

```
docker run --restart=always
```

See here for more details: 
https://docs.docker.com/engine/reference/commandline/run/#restart-policies---restart

**Comment by kfern** [comment]
@crscheid Thanks!
