### ISSUE TITLE
Persistent Data Causes a crash

### ISSUE THREAD

**Issue by slapidus** [crscheid/pocketmine-mp#4]
Works fine without persistent data but when I map a directory I get a slew of errors relating to unable to stream the resource directories.

**Comment by crscheid** [comment]
Glad to take a look. Can you post your config and the errors you are receiving?

**Comment by slapidus** [comment]
So somehow an update to docker fixed it completely.

**Comment by crscheid** [comment]
Good to hear. Will close this then.
